// Static leaderboard, generated by the most recent training run and committed
// to the repo so the dashboard renders its headline KPIs on first paint
// without waiting for an API call. Update this file after each retrain by
// pasting the contents of platform/data/models/leaderboard.json.
//
// Current values: production retrain 2026-06-29 with the NDCG-tuned blend
// weights (TF-IDF 0.45 / neural 0.30 / ALS 0.10 / popularity 0.15), k=10,
// 2,000 held-out seeds over the 28,436-paper catalogue.

export interface LeaderboardRow {
  algorithm: string;
  k: number;
  n_seeds_eval: number;
  "precision@k": number;
  "recall@k": number;
  "map@k": number;
  "ndcg@k": number;
  "hit_rate@k": number;
  coverage: number;
  diversity: number;
  ils: number;
  latency_p50_ms: number;
  latency_p95_ms: number;
}

export const LEADERBOARD: LeaderboardRow[] = [
  {
    algorithm: "popularity",
    k: 10,
    n_seeds_eval: 2000,
    "precision@k": 0.0031,
    "recall@k": 0.0293,
    "map@k": 0.0098,
    "ndcg@k": 0.0147,
    "hit_rate@k": 0.031,
    coverage: 0.0004,
    diversity: 0.957,
    ils: 0.043,
    latency_p50_ms: 0.15,
    latency_p95_ms: 0.2,
  },
  {
    algorithm: "tfidf",
    k: 10,
    n_seeds_eval: 2000,
    "precision@k": 0.0315,
    "recall@k": 0.307,
    "map@k": 0.1491,
    "ndcg@k": 0.1872,
    "hit_rate@k": 0.312,
    coverage: 0.386,
    diversity: 0.87,
    ils: 0.13,
    latency_p50_ms: 46.5,
    latency_p95_ms: 53.0,
  },
  {
    algorithm: "neural",
    k: 10,
    n_seeds_eval: 2000,
    "precision@k": 0.0273,
    "recall@k": 0.2659,
    "map@k": 0.1214,
    "ndcg@k": 0.156,
    "hit_rate@k": 0.271,
    coverage: 0.366,
    diversity: 0.869,
    ils: 0.132,
    latency_p50_ms: 3.73,
    latency_p95_ms: 4.64,
  },
  {
    algorithm: "als",
    k: 10,
    n_seeds_eval: 2000,
    "precision@k": 0.0133,
    "recall@k": 0.1275,
    "map@k": 0.0513,
    "ndcg@k": 0.0694,
    "hit_rate@k": 0.1325,
    coverage: 0.181,
    diversity: 0.58,
    ils: 0.42,
    latency_p50_ms: 0.35,
    latency_p95_ms: 0.73,
  },
  {
    algorithm: "hybrid",
    k: 10,
    n_seeds_eval: 2000,
    "precision@k": 0.0437,
    "recall@k": 0.4258,
    "map@k": 0.1993,
    "ndcg@k": 0.2541,
    "hit_rate@k": 0.4345,
    coverage: 0.272,
    diversity: 0.659,
    ils: 0.342,
    latency_p50_ms: 50.9,
    latency_p95_ms: 59.4,
  },
];
