// Static leaderboard, generated by the most recent training run and committed
// to the repo so the dashboard renders its headline KPIs on first paint
// without waiting for an API call. Update this file after each retrain by
// pasting the contents of platform/data/models/leaderboard.json.

export interface LeaderboardRow {
  algorithm: string;
  k: number;
  n_seeds_eval: number;
  "precision@k": number;
  "recall@k": number;
  "map@k": number;
  "ndcg@k": number;
  coverage: number;
  diversity: number;
  ils: number;
  latency_p50_ms: number;
  latency_p95_ms: number;
}

export const LEADERBOARD: LeaderboardRow[] = [
  {
    algorithm: "popularity",
    k: 10,
    n_seeds_eval: 2000,
    "precision@k": 0.0033,
    "recall@k": 0.0320,
    "map@k": 0.0101,
    "ndcg@k": 0.0155,
    coverage: 0.0004,
    diversity: 0.94,
    ils: 0.06,
    latency_p50_ms: 0.08,
    latency_p95_ms: 0.12,
  },
  {
    algorithm: "tfidf",
    k: 10,
    n_seeds_eval: 2000,
    "precision@k": 0.0317,
    "recall@k": 0.3110,
    "map@k": 0.1546,
    "ndcg@k": 0.1925,
    coverage: 0.387,
    diversity: 0.87,
    ils: 0.13,
    latency_p50_ms: 55.4,
    latency_p95_ms: 66.4,
  },
  {
    algorithm: "neural",
    k: 10,
    n_seeds_eval: 2000,
    "precision@k": 0.0277,
    "recall@k": 0.2709,
    "map@k": 0.1279,
    "ndcg@k": 0.1623,
    coverage: 0.366,
    diversity: 0.87,
    ils: 0.13,
    latency_p50_ms: 2.91,
    latency_p95_ms: 3.70,
  },
  {
    algorithm: "als",
    k: 10,
    n_seeds_eval: 2000,
    "precision@k": 0.0127,
    "recall@k": 0.1225,
    "map@k": 0.0392,
    "ndcg@k": 0.0588,
    coverage: 0.184,
    diversity: 0.57,
    ils: 0.43,
    latency_p50_ms: 0.31,
    latency_p95_ms: 0.68,
  },
  {
    algorithm: "hybrid",
    k: 10,
    n_seeds_eval: 2000,
    "precision@k": 0.0353,
    "recall@k": 0.3465,
    "map@k": 0.1665,
    "ndcg@k": 0.2101,
    coverage: 0.333,
    diversity: 0.56,
    ils: 0.44,
    latency_p50_ms: 61.2,
    latency_p95_ms: 75.4,
  },
];
